// Mocks generated by Mockito 5.4.4 from annotations
// in fake_store_joao/test/data/presentation/screen/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fake_store_joao/data/models/profile/user/user.dart' as _i5;
import 'package:fake_store_joao/data/repositories/authentication_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:result_dart/result_dart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<S extends Object, F extends Object> extends _i1.SmartFake
    implements _i2.Result<S, F> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i3.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<String, String>> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<String, String>>.value(
            _FakeResult_0<String, String>(
          this,
          Invocation.method(
            #loginUser,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<String, String>>);

  @override
  _i4.Future<_i2.Result<_i5.User, String>> getProfile(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [token],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.User, String>>.value(
            _FakeResult_0<_i5.User, String>(
          this,
          Invocation.method(
            #getProfile,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.User, String>>);
}
