name: "Make tests"   # You can name it as you want

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:   # Telling what jobs we need to happen
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
    # device we want our code to run on ( macos - ubuntu - windows )
    # here we selected macos-latest to be able to get ios build
    runs-on: macos-latest 

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
          channel: 'stable'
        
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Test flutter app
        run: flutter test
